'use client';

import React from 'react';
import { PageShell } from '@/components/layout/PageShell';

export default function TermsPage() {
    return (
        <PageShell>
            <div className="max-w-2xl mx-auto space-y-8 animate-in fade-in duration-500">
                <div className="space-y-2">
                    <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
                    <p className="text-muted-foreground">Last updated: December 2025</p>
                </div>

                <div className="prose dark:prose-invert">
                    <h3>1. Advisory Disclaimer</h3>
                    <p>
                        QMM Studio ("The Librarian") provides strategic guidance based on pattern matching and algorithmic models.
                        <strong>This is not legal, financial, or guaranteed professional advice.</strong>
                        You are responsible for verifying all claims, compliance requirements, and financial decisions before deploying campaigns.
                    </p>

                    <h3>2. Acceptable Use</h3>
                    <p>
                        You agree not to use this tool for:
                    </p>
                    <ul>
                        <li>Unlawful or deceptive marketing practices.</li>
                        <li>Generating content that promotes hate speech or harm.</li>
                        <li>Attempting to reverse-engineer the "Physics of Marketing" algorithms.</li>
                    </ul>

                    <h3>3. Intellectual Property</h3>
                    <p>
                        The strategies generated by the Librarian for your specific scenarios belong to you.
                        The underlying system, UI, and "Physics of Marketing" methodologies belong to QMM Studio.
                    </p>

                    <h3>4. Limitation of Liability</h3>
                    <p>
                        QMM Studio is provided "as is". We are not liable for any losses incurred from the execution of strategies suggested by the tool.
                    </p>
                </div>
            </div>
        </PageShell>
    );
}
